import { ProgramTypeId } from "../../../programTypes";
import {
  ChoreographicSequenceRule,
  DifficultPositionRule,
  FallPenaltyRule,
  IllegalElementRule,
  JumpBonusRule,
  JumpCombinationRule,
  JumpProgramRule,
  JumpRepetitionRule,
  JumpRotationCallRule,
  MandatoryPositionRule,
  MissingMandatoryElementRule,
  OfficialRulePack,
  ProgramTimeRule,
  RefereePenaltyRule,
  SequenceConfirmationRule,
  SequenceRestrictionRule,
  StarredElementRule,
  SpinCombinationRule,
  SpinConfirmationRule,
  SpinDefinitionRule,
  SpinProgramRule,
  SpinRestrictionRule,
  StepSequenceDefinitionRule,
  StepSequenceLevelRule,
  StepSequenceProgramRule,
  TechnicalPanelPenaltyRule,
  WorldSkate2026DraftRulePack,
} from "../../types";

const jumpDefinitions: JumpProgramRule[] = [
  {
    ruleId: "JUMP-DEF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Jump element",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A jump element is the airborne technical family used for takeoff and landing actions in free skating.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed structural definition for jump handling.",
  },
  {
    ruleId: "JUMP-DEF-002",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Solo jump",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A solo jump is executed as a standalone element rather than as part of a combination or sequence.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed structural definition for standalone jump handling.",
  },
  {
    ruleId: "JUMP-DEF-003",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Combination jump",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A combination jump links more than one jump in a continuous technical element.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed structural definition for combination handling.",
  },
  {
    ruleId: "JUMP-DEF-009",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Entry of a jump",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Jump-entry terminology must be preserved for technical calling and future element-catalogue mapping.",
    implementationTargets: ["Technical Calling", "Element Catalogue"],
    confidence: "confirmed",
    notes: "Confirmed entry terminology for later element mapping.",
  },
];

const shortProgramJumpRules: JumpProgramRule[] = [
  {
    ruleId: "SP-JUMP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Espoir",
    categories: ["espoir"],
    programTypes: ["short"],
    summary:
      "Espoir short program includes a mandatory Axel requirement and a category-specific jump structure.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed short-program structure for Espoir.",
  },
  {
    ruleId: "SP-JUMP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Cadet",
    categories: ["cadet"],
    programTypes: ["short"],
    summary:
      "Cadet short program includes a mandatory Axel and category-specific solo and combination restrictions.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed short-program structure for Cadet.",
  },
  {
    ruleId: "SP-JUMP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Youth",
    categories: ["youth"],
    programTypes: ["short"],
    summary:
      "Youth short program includes a mandatory Axel and category-specific solo and combination restrictions.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed short-program structure for Youth.",
  },
  {
    ruleId: "SP-JUMP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Junior",
    categories: ["junior"],
    programTypes: ["short"],
    summary:
      "Junior short program includes a mandatory Axel and category-specific solo and combination restrictions.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed short-program structure for Junior.",
  },
  {
    ruleId: "SP-JUMP-005",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Senior",
    categories: ["senior"],
    programTypes: ["short"],
    summary:
      "Senior short program includes a mandatory Axel and category-specific solo and combination restrictions.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed short-program structure for Senior.",
  },
  {
    ruleId: "SP-JUMP-010",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Repeated jump rule",
    categories: ["espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["short"],
    summary:
      "Only one chosen jump may be repeated in the short program, and one occurrence must appear in combination.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed repeated-jump structure for the short program.",
  },
];

const longProgramJumpRules: JumpProgramRule[] = [
  {
    ruleId: "LP-JUMP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Tots",
    categories: ["tots"],
    programTypes: ["long"],
    summary:
      "Tots long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Tots.",
  },
  {
    ruleId: "LP-JUMP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Minis",
    categories: ["minis"],
    programTypes: ["long"],
    summary:
      "Minis long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Minis.",
  },
  {
    ruleId: "LP-JUMP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Espoir",
    categories: ["espoir"],
    programTypes: ["long"],
    summary:
      "Espoir long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Espoir.",
  },
  {
    ruleId: "LP-JUMP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Cadet",
    categories: ["cadet"],
    programTypes: ["long"],
    summary:
      "Cadet long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Cadet.",
  },
  {
    ruleId: "LP-JUMP-005",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Youth",
    categories: ["youth"],
    programTypes: ["long"],
    summary:
      "Youth long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Youth.",
  },
  {
    ruleId: "LP-JUMP-006",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Junior",
    categories: ["junior"],
    programTypes: ["long"],
    summary:
      "Junior long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Junior.",
  },
  {
    ruleId: "LP-JUMP-007",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Senior",
    categories: ["senior"],
    programTypes: ["long"],
    summary:
      "Senior long program uses category-specific jump-count and repetition constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Senior.",
  },
  {
    ruleId: "LP-JUMP-008",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Mandatory Axel or mandatory jumps",
    categories: ["tots", "minis", "espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["long"],
    summary:
      "The long program includes mandatory jump requirements that differ by category and must remain category-specific.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed mandatory-jump structure for the long program.",
  },
  {
    ruleId: "LP-JUMP-009",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Repetition limits",
    categories: ["tots", "minis", "espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["long"],
    summary:
      "Repetition limits differ by category and must be stored separately from general jump-count limits.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed repetition-structure distinction for the long program.",
  },
  {
    ruleId: "LP-JUMP-010",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Repeated jump in combination",
    categories: ["tots", "minis", "espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["long"],
    summary:
      "When a jump is repeated, one repeated occurrence must appear in combination according to the documented long-program procedure.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed repeated-jump procedure for the long program.",
  },
];

const combinationRules: JumpCombinationRule[] = [
  {
    ruleId: "COMBO-001",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Valid combination",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A valid combination links jumps in a continuous technical sequence without breaking the jump chain.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed combination definition.",
  },
  {
    ruleId: "COMBO-005",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Broken combinations",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A broken combination must be distinguished from a valid one and preserved for technical-calling interpretation.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed broken-combination handling.",
  },
  {
    ruleId: "COMBO-006",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Saved combinations",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Saved combinations are documented for later validation and must not be collapsed into regular repeated-jump logic.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed saved-combination handling.",
  },
];

const repetitionRules: JumpRepetitionRule[] = [
  {
    ruleId: "REP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Short Program repetition",
    categories: ["espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["short"],
    summary:
      "Only one chosen jump may be repeated in the short program, and one occurrence must appear in combination.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed short-program repetition structure.",
  },
  {
    ruleId: "REP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Long Program repetition",
    categories: ["tots", "minis", "espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["long"],
    summary:
      "Long-program repetition limits are category-specific and must be stored separately by category.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed long-program repetition structure.",
  },
  {
    ruleId: "REP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Minis/Tots special repetition limits",
    categories: ["minis", "tots"],
    programTypes: ["long"],
    summary:
      "Minis and Tots use special repetition limits that must be preserved as separate category logic.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed Minis/Tots special repetition handling.",
  },
  {
    ruleId: "REP-005",
    sourceId: "WS-FREE-2026",
    printedPage: "39-43",
    pdfPage: "39-43",
    section: "Repeated solo jump vs repeated combination content",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A repeated solo jump is not equivalent to repeated combination content; the two cases must remain distinct in validation logic.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed distinction between repeated solo and repeated combination content.",
  },
];

const rotationCalls: JumpRotationCallRule[] = [
  {
    ruleId: "ROT-001",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Complete rotation",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Complete rotation is the baseline technical state for a jump and is distinct from under-rotation or downgrade calls.",
    implementationTargets: ["Technical Calling", "Scoring / RollArt dependency"],
    confidence: "confirmed",
    notes: "Confirmed rotation baseline.",
  },
  {
    ruleId: "ROT-002",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Under-rotated <",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Under-rotation uses the `<` call notation and must be preserved as a distinct state.",
    implementationTargets: ["Technical Calling", "Scoring / RollArt dependency"],
    confidence: "confirmed",
    notes: "Confirmed under-rotation notation.",
  },
  {
    ruleId: "ROT-003",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Half-rotated <<",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Half-rotation uses the `<<` call notation and must be preserved as a distinct state.",
    implementationTargets: ["Technical Calling", "Scoring / RollArt dependency"],
    confidence: "confirmed",
    notes: "Confirmed half-rotation notation.",
  },
  {
    ruleId: "ROT-004",
    sourceId: "WS-FREE-2026",
    printedPage: "10-12",
    pdfPage: "10-12",
    section: "Downgraded <<<",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Downgrade uses the `<<<` call notation and must be preserved as a distinct state.",
    implementationTargets: ["Technical Calling", "Scoring / RollArt dependency"],
    confidence: "confirmed",
    notes: "Confirmed downgrade notation.",
  },
];

const spinProgramRules: SpinProgramRule[] = [
  {
    ruleId: "SPIN-SP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Junior and Senior short program spins",
    categories: ["junior", "senior"],
    programTypes: ["short"],
    summary:
      "Junior and Senior short programs require one one-position spin and one combination spin; the combination includes sit and allows up to four positions.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed structural short-program spin requirement.",
  },
  {
    ruleId: "SPIN-SP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Cadet and Youth short program spins",
    categories: ["cadet", "youth"],
    programTypes: ["short"],
    summary:
      "Cadet and Youth short programs require one one-position spin and one combination spin, including mandatory sit where specified.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed structural short-program spin requirement.",
  },
  {
    ruleId: "SPIN-SP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Espoir short program one-position spin",
    categories: ["espoir"],
    programTypes: ["short"],
    summary:
      "Espoir one-position spin must be camel and cannot duplicate the camel used in the combination spin.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed Espoir camel restriction.",
  },
  {
    ruleId: "SPIN-SP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Espoir short program combination spin",
    categories: ["espoir"],
    programTypes: ["short"],
    summary:
      "Espoir combination spin includes exactly one sit and one camel with a maximum of two positions.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Espoir short-program combination structure.",
  },
  {
    ruleId: "SPIN-LP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Youth/Junior/Senior long program spins",
    categories: ["youth", "junior", "senior"],
    programTypes: ["long"],
    summary:
      "Maximum two spin elements; one combination including sit; maximum four positions; both spins must be different.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed long-program structure for Youth/Junior/Senior.",
  },
  {
    ruleId: "SPIN-LP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Cadet long program spins",
    categories: ["cadet"],
    programTypes: ["long"],
    summary:
      "Maximum two spin elements; one combination including sit; broken not allowed; both spins must be different.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Cadet long-program spin restrictions.",
  },
  {
    ruleId: "SPIN-LP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Espoir long program spins",
    categories: ["espoir"],
    programTypes: ["long"],
    summary:
      "Two spin elements; one combination including sit; broken not allowed; both spins must be different.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Espoir long-program spin restrictions.",
  },
  {
    ruleId: "SPIN-LP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Minis long program spins",
    categories: ["minis"],
    programTypes: ["long"],
    summary:
      "Two spin elements; one combination including sit; broken ankle, heel and inverted are not allowed; both spins must be different.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Minis long-program spin restrictions.",
  },
  {
    ruleId: "SPIN-LP-005",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Tots long program spins",
    categories: ["tots"],
    programTypes: ["long"],
    summary:
      "Two spin elements including one combination; only upright and sit positions allowed; Biellmann not allowed; max four positions in combination; spins must differ.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Tots long-program spin restrictions.",
  },
];

const spinDefinitionRules: SpinDefinitionRule[] = [
  {
    ruleId: "SPIN-DEF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "One-position spin",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "One-position spin is a spin element with one basic position and confirmation requirements.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed one-position spin definition.",
  },
  {
    ruleId: "SPIN-DEF-002",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Combination spin",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Combination spin includes multiple positions and each position is subject to confirmation rules.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed combination spin definition.",
  },
  {
    ruleId: "SPIN-DEF-003",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Basic positions",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Basic spin positions include upright, sit, camel, broken, heel, and inverted, with category-specific restrictions.",
    implementationTargets: ["Validation Engine", "Element Catalogue", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed structural position families.",
  },
  {
    ruleId: "SPIN-DEF-006",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Change of foot",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Change of foot is part of combination-spin structure and must respect sequence restrictions.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed structural change-of-foot concept.",
  },
  {
    ruleId: "SPIN-DEF-007",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Spin confirmation",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Spins and positions are either confirmed or not confirmed based on structural minimums and execution.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed confirmation-state model.",
  },
];

const spinConfirmationRules: SpinConfirmationRule[] = [
  {
    ruleId: "SPIN-CONF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Minimum rotations one-position",
    categories: ["general"],
    programTypes: ["all"],
    summary: "One-position spin requires at least three rotations for confirmation.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed minimum rotation threshold.",
  },
  {
    ruleId: "SPIN-CONF-002",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Minimum rotations per combination position",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Combination spin requires at least two rotations per position for each position to be confirmed.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed position-level minimum rotation threshold.",
  },
  {
    ruleId: "SPIN-CONF-003",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Required position achievement",
    categories: ["general"],
    programTypes: ["all"],
    summary: "Required position must be clearly achieved to satisfy structural requirement.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed required-position achievement rule.",
  },
  {
    ruleId: "SPIN-CONF-005",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Positions confirmed before fall in combination",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Positions completed before a fall in a combination may remain confirmed when minimum rotations were achieved.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed pre-fall confirmation carryover.",
  },
];

const spinCombinationRules: SpinCombinationRule[] = [
  {
    ruleId: "SPIN-COMB-001",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Maximum positions in combination",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Combination spins have maximum position counts defined by category and program type.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed combination-position maximum structure.",
  },
  {
    ruleId: "SPIN-COMB-002",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Consecutive change of foot restrictions",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Consecutive foot changes are structurally restricted and must be validated in sequence logic.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed consecutive change-of-foot restriction.",
  },
  {
    ruleId: "SPIN-COMB-003",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Clear axis change",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Axis change must be clearly achieved where required by combination-spin structure.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed axis-change structure.",
  },
  {
    ruleId: "SPIN-COMB-005",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Combination break situations",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Specific interruptions break a combination spin and must be handled separately from confirmed positions.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed break-condition structure.",
  },
  {
    ruleId: "SPIN-COMB-006",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Confirmed positions before break or fall",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Confirmed positions before a break/fall can remain confirmed if minimum rotations were completed.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed pre-break confirmation handling.",
  },
  {
    ruleId: "SPIN-COMB-007",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Two spins must be different",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Where specified, two spins in the program must be different and duplicate structure is not allowed.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed spin-difference requirement.",
  },
];

const spinRestrictionRules: SpinRestrictionRule[] = [
  {
    ruleId: "SPIN-REP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Same kind maximum presentations",
    categories: ["category-specific"],
    programTypes: ["short", "long"],
    summary:
      "The same kind of spin cannot be performed more than twice where specified.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed same-kind presentation limit.",
  },
  {
    ruleId: "SPIN-REP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Difficult position reuse limit",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Difficult positions may be used only once per program where specified.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed difficult-position reuse limit.",
  },
  {
    ruleId: "SPIN-REP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Broken ankle category allowance",
    categories: ["junior", "senior"],
    programTypes: ["short", "long"],
    summary:
      "Broken ankle position is allowed only in Junior and Senior categories.",
    implementationTargets: ["Validation Engine", "Element Catalogue"],
    confidence: "confirmed",
    notes: "Confirmed category-scoped broken-ankle allowance.",
  },
  {
    ruleId: "SPIN-REP-005",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Broken ankle maximum count",
    categories: ["junior", "senior"],
    programTypes: ["short", "long"],
    summary:
      "Broken ankle position may appear a maximum of two times per program.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed broken-ankle count limit.",
  },
  {
    ruleId: "SPIN-REP-006",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Excess-spin treatment",
    categories: ["category-specific"],
    programTypes: ["short", "long"],
    summary:
      "Excess-spin handling follows category/program structural limits and must be traceable.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed excess-spin structural handling.",
  },
  {
    ruleId: "SPIN-LP-006",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Cadet and Espoir broken restriction",
    categories: ["cadet", "espoir"],
    programTypes: ["long"],
    summary: "Broken position is not allowed in Cadet and Espoir long programs.",
    implementationTargets: ["Validation Engine", "Element Catalogue"],
    confidence: "confirmed",
    notes: "Confirmed category-specific broken restriction.",
  },
  {
    ruleId: "SPIN-LP-007",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Minis inverted and heel restrictions",
    categories: ["minis"],
    programTypes: ["long"],
    summary:
      "In Minis long program, inverted and heel positions are not allowed alongside broken ankle restrictions.",
    implementationTargets: ["Validation Engine", "Element Catalogue"],
    confidence: "confirmed",
    notes: "Confirmed Minis structural position restrictions.",
  },
  {
    ruleId: "SPIN-LP-008",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Tots Biellmann restriction",
    categories: ["tots"],
    programTypes: ["long"],
    summary: "Biellmann position is not allowed in Tots long program.",
    implementationTargets: ["Validation Engine", "Element Catalogue"],
    confidence: "confirmed",
    notes: "Confirmed Tots Biellmann restriction.",
  },
];

const difficultPositionRules: DifficultPositionRule[] = [
  {
    ruleId: "SPIN-DIFF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Upright difficult positions",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Catalogue set for upright difficult positions includes forward, layback, split, Biellmann, torso, and heel variants.",
    implementationTargets: ["Element Catalogue", "Technical Calling"],
    confidence: "confirmed",
    notes: "Structural catalogue entry only; no scoring data.",
  },
  {
    ruleId: "SPIN-DIFF-002",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Sit difficult positions",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Catalogue set for sit difficult positions includes forward, sideways, behind, and twist variants.",
    implementationTargets: ["Element Catalogue", "Technical Calling"],
    confidence: "confirmed",
    notes: "Structural catalogue entry only; no scoring data.",
  },
  {
    ruleId: "SPIN-DIFF-003",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Camel difficult positions",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Catalogue set for camel difficult positions includes layover, inverted, Bryant, forward, and sideways variants.",
    implementationTargets: ["Element Catalogue", "Technical Calling"],
    confidence: "confirmed",
    notes: "Structural catalogue entry only; no scoring data.",
  },
  {
    ruleId: "SPIN-DIFF-004",
    sourceId: "WS-FREE-2026",
    printedPage: "13-22",
    pdfPage: "13-22",
    section: "Broken and heel variations",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Catalogue set includes broken and heel variations for structural identification only.",
    implementationTargets: ["Element Catalogue", "Technical Calling"],
    confidence: "confirmed",
    notes: "Structural catalogue entry only; no scoring data.",
  },
];

const stepSequenceProgramRules: StepSequenceProgramRule[] = [
  {
    ruleId: "SEQ-SP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "Short program Junior/Senior",
    categories: ["junior", "senior"],
    programTypes: ["short"],
    summary:
      "One step sequence is mandatory with a maximum duration of forty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed short-program sequence requirement.",
  },
  {
    ruleId: "SEQ-SP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "Short program Youth",
    categories: ["youth"],
    programTypes: ["short"],
    summary:
      "One step sequence is mandatory, maximum level 4, maximum duration forty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Youth sequence cap and duration.",
  },
  {
    ruleId: "SEQ-SP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "Short program Cadet",
    categories: ["cadet"],
    programTypes: ["short"],
    summary:
      "One step sequence is mandatory, maximum level 3, maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Cadet sequence cap and duration.",
  },
  {
    ruleId: "SEQ-SP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "Short program Espoir",
    categories: ["espoir"],
    programTypes: ["short"],
    summary:
      "One step sequence is mandatory, maximum level 3, maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Espoir sequence cap and duration.",
  },
  {
    ruleId: "SEQ-LP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "8",
    pdfPage: "8",
    section: "Long program Youth/Junior/Senior",
    categories: ["youth", "junior", "senior"],
    programTypes: ["long"],
    summary:
      "Long program requires one choreographic sequence with maximum level 1 and maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed choreographic-sequence profile.",
  },
  {
    ruleId: "SEQ-LP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "8",
    pdfPage: "8",
    section: "Long program Cadet",
    categories: ["cadet"],
    programTypes: ["long"],
    summary:
      "Long program requires one choreographic sequence with maximum level 1 and maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Cadet choreographic requirement.",
  },
  {
    ruleId: "SEQ-LP-003",
    sourceId: "WS-FREE-2026",
    printedPage: "8",
    pdfPage: "8",
    section: "Long program Espoir",
    categories: ["espoir"],
    programTypes: ["long"],
    summary:
      "Long program requires one choreographic sequence with maximum level 1 and maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Espoir choreographic requirement.",
  },
  {
    ruleId: "SEQ-LP-004",
    sourceId: "WS-FREE-2026",
    printedPage: "9",
    pdfPage: "9",
    section: "Long program Minis",
    categories: ["minis"],
    programTypes: ["long"],
    summary:
      "Long program requires one step sequence, maximum level 2, maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Minis step-sequence requirement.",
  },
  {
    ruleId: "SEQ-LP-005",
    sourceId: "WS-FREE-2026",
    printedPage: "9",
    pdfPage: "9",
    section: "Long program Tots",
    categories: ["tots"],
    programTypes: ["long"],
    summary:
      "Long program requires one step sequence, maximum level 1, with specific confirmed step/turn set and maximum duration thirty seconds.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Tots specific sequence requirement.",
  },
];

const stepSequenceDefinitionRules: StepSequenceDefinitionRule[] = [
  {
    ruleId: "STEP-DEF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "One-foot turns / two-feet turns / steps",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Step sequence technical content is formed by defined turn and step families.",
    implementationTargets: ["Element Catalogue", "Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed step content definitions.",
  },
  {
    ruleId: "STEP-DEF-002",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Start and end structure",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Step sequence uses a free pattern with category time limits and call-flow start/end handling.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed structural start/end behavior.",
  },
  {
    ruleId: "STEP-DEF-003",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Surface and pattern use",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Pattern is free and sequence construction may use the skating surface under category limits.",
    implementationTargets: ["Smart Builder", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed free-pattern structure.",
  },
  {
    ruleId: "STEP-DEF-004",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Cluster definition",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "A cluster is a sequence of at least three different one-foot turns.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed cluster structure.",
  },
  {
    ruleId: "STEP-DEF-005",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Body movements",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Body movements must clearly affect balance and involve at least two body parts.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed body-movement requirement.",
  },
  {
    ruleId: "STEP-DEF-006",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Turns counted and quality conditions",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Turns count only when technically correct with clear edge quality and valid execution.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed turn-counting quality criteria.",
  },
  {
    ruleId: "STEP-DEF-008",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Minimum technical content for level counting",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Level counting depends on confirmed turns/features with distribution constraints.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed minimum technical content structure.",
  },
  {
    ruleId: "STEP-DEF-009",
    sourceId: "WS-FREE-2026",
    printedPage: "35",
    pdfPage: "35",
    section: "Not confirmed call state in sequences",
    categories: ["general"],
    programTypes: ["all"],
    summary:
      "Technical panel may call turns as confirmed/not confirmed and features as confirmed for level determination.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed sequence call-state model.",
  },
];

const stepSequenceLevelRules: StepSequenceLevelRule[] = [
  {
    ruleId: "STEP-LVL-BASE",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Footwork base level",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Base level requires basic footwork requirements and calling-specification compliance.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed base-level structure.",
  },
  {
    ruleId: "STEP-LVL-1",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Footwork level 1",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Level 1 requires base-level compliance plus four turns and one required feature.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed level 1 structure.",
  },
  {
    ruleId: "STEP-LVL-2",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Footwork level 2",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Level 2 requires base-level compliance plus six turns and two different features.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed level 2 structure.",
  },
  {
    ruleId: "STEP-LVL-3",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Footwork level 3",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Level 3 requires base-level compliance plus eight turns and three different features.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed level 3 structure.",
  },
  {
    ruleId: "STEP-LVL-4",
    sourceId: "WS-FREE-2026",
    printedPage: "22",
    pdfPage: "22",
    section: "Footwork level 4",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Level 4 requires base-level compliance plus ten turns and four different features.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed level 4 structure.",
  },
  {
    ruleId: "STEP-LVL-FEAT",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Feature definitions and distribution",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Feature set includes body movements, choctaws, clusters, and distribution of turns across feet/directions.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed feature framework for level building.",
  },
  {
    ruleId: "STEP-LVL-TOTS",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Tots level-1 special rule",
    categories: ["tots"],
    programTypes: ["long"],
    summary:
      "Tots level 1 requires one confirmed instance of each required step/turn type, with no feature confirmation requirement.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed Tots special level structure.",
  },
];

const choreographicSequenceRules: ChoreographicSequenceRule[] = [
  {
    ruleId: "CHSEQ-DEF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Choreo sequence base definition",
    categories: ["youth", "junior", "senior", "cadet", "espoir"],
    programTypes: ["long"],
    summary:
      "Choreographic sequence has free pattern, includes steps/linking steps, and has a thirty-second time limit.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed choreographic sequence base structure.",
  },
  {
    ruleId: "CHSEQ-LVL-001",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Choreo max level",
    categories: ["youth", "junior", "senior", "cadet", "espoir"],
    programTypes: ["long"],
    summary:
      "Choreographic sequence structure includes base and level 1 only for affected categories.",
    implementationTargets: ["Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed choreographic level cap.",
  },
  {
    ruleId: "CHSEQ-FEAT-001",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Choreo level feature structure",
    categories: ["youth", "junior", "senior", "cadet", "espoir"],
    programTypes: ["long"],
    summary:
      "Choreographic level feature requires up to three counted turns from specified families with originality/spectacularity condition.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed choreographic feature structure.",
  },
  {
    ruleId: "CHSEQ-CONF-001",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Turn confirmation for choreo level",
    categories: ["youth", "junior", "senior", "cadet", "espoir"],
    programTypes: ["long"],
    summary:
      "Turns count only when technically correct with clear edge quality and valid execution conditions.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed choreographic confirmation quality rule.",
  },
  {
    ruleId: "CHSEQ-DIFF-002",
    sourceId: "WS-FREE-2026",
    printedPage: "23",
    pdfPage: "23",
    section: "Difference from technical step sequence",
    categories: ["youth", "junior", "senior", "cadet", "espoir"],
    programTypes: ["long"],
    summary:
      "Choreographic sequence uses a separate level and feature structure from technical step sequence definitions.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed structural distinction between sequence types.",
  },
];

const sequenceConfirmationRules: SequenceConfirmationRule[] = [
  {
    ruleId: "SEQ-CALL-001",
    sourceId: "WS-FREE-2026",
    printedPage: "35",
    pdfPage: "35",
    section: "Footwork start + level call",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Footwork call structure uses explicit start call and final level call.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed sequence calling baseline.",
  },
  {
    ruleId: "SEQ-CALL-002",
    sourceId: "WS-FREE-2026",
    printedPage: "35",
    pdfPage: "35",
    section: "Start and end identification",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Panel calls start when sequence begins and ends call on time signal or transition to next element.",
    implementationTargets: ["Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed call boundary handling.",
  },
  {
    ruleId: "SEQ-CALL-003",
    sourceId: "WS-FREE-2026",
    printedPage: "35",
    pdfPage: "35",
    section: "Timing control",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Panel timing operates against category maximum with documented tolerance window.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed timing control structure.",
  },
  {
    ruleId: "SEQ-CALL-004",
    sourceId: "WS-FREE-2026",
    printedPage: "35",
    pdfPage: "35",
    section: "Confirmed/not confirmed turn calls",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Panel can call turns as confirmed or not confirmed and features as confirmed.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed turn/feature confirmation call path.",
  },
];

const sequenceRestrictionRules: SequenceRestrictionRule[] = [
  {
    ruleId: "SEQ-GEN-001",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "General excess-element treatment",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Elements in excess are called but starred out and receive no value.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed excess-element treatment.",
  },
  {
    ruleId: "SEQ-GEN-002",
    sourceId: "WS-FREE-2026",
    printedPage: "35",
    pdfPage: "35",
    section: "Footwork timing tolerance",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Timing up to the maximum is accepted within panel tolerance for capped sequence durations.",
    implementationTargets: ["Technical Calling", "Validation Engine"],
    confidence: "confirmed",
    notes: "Confirmed duration tolerance behavior.",
  },
  {
    ruleId: "PROG-SEQ-001",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Mandatory sequence by category/program",
    categories: ["junior", "senior", "cadet", "youth", "espoir", "minis", "tots"],
    programTypes: ["short", "long"],
    summary:
      "Sequence type and count are profile-specific: short programs use step sequence; long programs use choreographic for some categories and step for Minis/Tots.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed profile-specific mandatory sequence mapping.",
  },
  {
    ruleId: "PROG-SEQ-002",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "One required sequence element",
    categories: ["junior", "senior", "cadet", "youth", "espoir", "minis", "tots"],
    programTypes: ["short", "long"],
    summary:
      "Program composition defines one required sequence element for each relevant category/program profile.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed required sequence count.",
  },
  {
    ruleId: "PROG-SEQ-003",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "Excess sequence treatment",
    categories: ["general"],
    programTypes: ["short", "long"],
    summary:
      "Excess technical elements are starred out with no value, applying to sequence excess as part of technical content.",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed sequence excess outcome where applicable.",
  },
  {
    ruleId: "PROG-SEQ-005",
    sourceId: "WS-FREE-2026",
    printedPage: "7-10",
    pdfPage: "7-10",
    section: "Category/program differences",
    categories: ["junior", "senior", "cadet", "youth", "espoir", "minis", "tots"],
    programTypes: ["short", "long"],
    summary:
      "Sequence type, level caps, and duration caps vary by category/program profile and must be stored profile-wise.",
    implementationTargets: ["Validation Engine", "Smart Builder"],
    confidence: "confirmed",
    notes: "Confirmed profile-dependent sequence structure.",
  },
];

const refereePenaltyRules: RefereePenaltyRule[] = [
  {
    ruleId: "REF-PEN-001",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger:
      "Kneeling or laying on the floor more than once or more than five seconds.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed referee fixed deduction.",
  },
  {
    ruleId: "REF-PEN-002",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Costume violation (with opinion of judges).",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed referee costume deduction.",
  },
  {
    ruleId: "REF-PEN-003",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Program time less than minimum or more than maximum.",
    consequence: "Deduct 0.5 point each 10 seconds or part thereof.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "UI / Referee controls",
    ],
    confidence: "confirmed",
    notes: "Confirmed duration penalty unit and partial-unit treatment.",
  },
  {
    ruleId: "REF-PEN-004",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger:
      "Time from start of music to first movement is greater than ten seconds.",
    consequence: "Deduct 0.5 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed music-to-movement delay deduction.",
  },
  {
    ruleId: "REF-PEN-005",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger:
      "Music with inappropriate or expletive lyrics, or spoken words in violation of general rules.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed referee music-content deduction.",
  },
  {
    ruleId: "REF-PEN-006",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger:
      "Skating outside designated competition surface or touching the barrier during program.",
    consequence: "Deduct 0.5 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed surface/boundary deduction.",
  },
  {
    ruleId: "REF-PEN-007",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Entry and exit floor timing not respecting allowed time.",
    consequence: "Deduct 0.5 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed entry/exit timing deduction.",
  },
  {
    ruleId: "REF-PEN-008",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Falls.",
    consequence:
      "Apply fall deductions: first and second fall are 1.0 each, then category-group progressive increases.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed fall penalty family entry.",
  },
];

const technicalPanelPenaltyRules: TechnicalPanelPenaltyRule[] = [
  {
    ruleId: "TP-PEN-001",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Technical Panel",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger:
      "More than one rotation jump or more than one jump in footwork sequence.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
    ],
    confidence: "confirmed",
    notes: "Confirmed TP footwork jump excess deduction.",
  },
  {
    ruleId: "TP-PEN-002",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Technical Panel",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Missing mandatory element.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
    ],
    confidence: "confirmed",
    notes: "Confirmed TP missing mandatory deduction.",
  },
  {
    ruleId: "TP-PEN-003",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Technical Panel",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Illegal element.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
    ],
    confidence: "confirmed",
    notes: "Confirmed TP illegal-element deduction.",
  },
  {
    ruleId: "TP-PEN-004",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Technical Panel",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Mandatory position in a spin element not attempted.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
    ],
    confidence: "confirmed",
    notes: "Confirmed TP mandatory-position deduction.",
  },
];

const fallPenaltyRules: FallPenaltyRule[] = [
  {
    ruleId: "FALL-001",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "First fall.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed first-fall deduction.",
  },
  {
    ruleId: "FALL-002",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Second fall.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed second-fall deduction.",
  },
  {
    ruleId: "FALL-003",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["tots", "minis"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Each fall after second in Tots/Minis.",
    consequence: "Increase penalty by 0.3 for each subsequent fall.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed category-specific progressive increment for Tots/Minis.",
  },
  {
    ruleId: "FALL-004",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Each fall after second in Espoir through Senior.",
    consequence: "Increase penalty by 0.5 for each subsequent fall.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed category-specific progressive increment for Espoir to Senior.",
  },
  {
    ruleId: "FALL-005",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Falls quick reference chart",
    categories: ["tots", "minis"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Falls 1 through 6 in Tots/Minis.",
    consequence: "Cumulative deductions are 1.0, 2.0, 3.3, 4.9, 6.8, 9.0.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed chart values; do not extrapolate beyond chart.",
  },
  {
    ruleId: "FALL-006",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Falls quick reference chart",
    categories: ["espoir", "cadet", "youth", "junior", "senior"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Falls 1 through 6 in Espoir through Senior.",
    consequence: "Cumulative deductions are 1.0, 2.0, 3.5, 5.5, 8.0, 11.0.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed chart values; do not extrapolate beyond chart.",
  },
  {
    ruleId: "FALL-007",
    sourceId: "WS-FREE-2026",
    printedPage: "29-30",
    pdfPage: "29-30",
    section: "Technical panel protocol and guidelines",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Specialist",
    trigger: "Fall event during program.",
    consequence:
      "TS calls falls; referee confirms falls and has final word if there is doubt.",
    affectedScore: "program timing control",
    applicationMode: "technical-call",
    implementationTargets: ["Technical Calling", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed TS-to-referee fall workflow.",
  },
];

const missingMandatoryElementRules: MissingMandatoryElementRule[] = [
  {
    ruleId: "MME-001",
    sourceId: "WS-FREE-2026",
    printedPage: "53",
    pdfPage: "53",
    section: "Missing mandatory element",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Mandatory element omitted or not attempted.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Validation Engine", "Deduction Engine"],
    confidence: "confirmed",
    notes: "Confirmed missing mandatory element penalty definition.",
  },
  {
    ruleId: "MME-002",
    sourceId: "WS-FREE-2026",
    printedPage: "53",
    pdfPage: "53",
    section: "Missing mandatory element",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger:
      "Element was attempted even with fall, mistake, or timeout modifying original group.",
    consequence: "Do not apply missing mandatory element penalty for that attempt.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Validation Engine", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed attempted-versus-not-attempted distinction.",
  },
  {
    ruleId: "MME-003",
    sourceId: "WS-FREE-2026",
    printedPage: "53",
    pdfPage: "53",
    section: "Missing mandatory element",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Automatic Scoring System",
    trigger:
      "Compulsory element not included by the last chance in the corresponding element group.",
    consequence:
      "Last element of same group is starred out with no value; missing mandatory deduction also applies.",
    affectedScore: "technical content element value",
    applicationMode: "automatic",
    implementationTargets: ["Validation Engine", "Scoring", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed star/no-value treatment linked to missing mandatory.",
  },
  {
    ruleId: "MME-004",
    sourceId: "WS-FREE-2026",
    printedPage: "53",
    pdfPage: "53",
    section: "Missing mandatory element examples",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Two combo spins used where one mandatory solo spin is required.",
    consequence:
      "Second combo spin is starred/no value and missing mandatory element penalty applies.",
    affectedScore: "technical content element value",
    applicationMode: "manual",
    implementationTargets: ["Validation Engine", "Scoring", "Deduction Engine"],
    confidence: "confirmed",
    notes: "Confirmed mandatory-box relationship example for spin group.",
  },
];

const illegalElementRules: IllegalElementRule[] = [
  {
    ruleId: "ILL-001",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Illegal element",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Element expressly prohibited in the program is included.",
    consequence: "Classify as illegal element; apply technical-panel illegal-element penalty.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
    ],
    confidence: "confirmed",
    notes: "Confirmed illegal element definition.",
  },
  {
    ruleId: "ILL-002",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Illegal element examples",
    categories: ["espoir", "minis"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger:
      "Category-prohibited examples such as 2A in Espoir/Mini, second one-rotation jump in footwork sequence, or broken position in Espoir.",
    consequence: "Mark illegal and apply technical-panel penalty.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
    ],
    confidence: "confirmed",
    notes: "Confirmed profile-specific illegal examples.",
  },
  {
    ruleId: "ILL-003",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Illegal element - extra allowed items",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Automatic Scoring System",
    trigger: "Extra item is in excess but still allowed in that category.",
    consequence:
      "System stars item with no value; no illegal penalty is applied for this case.",
    affectedScore: "technical content element value",
    applicationMode: "automatic",
    implementationTargets: ["Validation Engine", "Scoring", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed distinction between illegal and allowed excess.",
  },
];

const mandatoryPositionRules: MandatoryPositionRule[] = [
  {
    ruleId: "MSP-001",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Mandatory position in a spin element",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Mandatory position is omitted or not attempted.",
    consequence: "Deduct 1.0 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Validation Engine", "Deduction Engine"],
    confidence: "confirmed",
    notes: "Confirmed mandatory-position deduction.",
  },
  {
    ruleId: "MSP-002",
    sourceId: "WS-FREE-2026",
    printedPage: "54",
    pdfPage: "54",
    section: "Mandatory position note",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger:
      "Fall or other error prevents completion; mandatory sit is assumed attempted but no sit is presented elsewhere.",
    consequence:
      "No missing-mandatory-element penalty for attempt state; combination is starred and receives no value.",
    affectedScore: "technical content element value",
    applicationMode: "manual",
    implementationTargets: ["Validation Engine", "Technical Calling", "Scoring"],
    confidence: "confirmed",
    notes: "Confirmed attempted-versus-achieved distinction without using unresolved percentage effects.",
  },
];

const starredElementRules: StarredElementRule[] = [
  {
    ruleId: "STAR-001",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "General",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Automatic Scoring System",
    trigger: "Attempts occupy boxes; subsequent elements exceed allowed boxes.",
    consequence: "Subsequent elements are starred and have no value (0).",
    affectedScore: "technical content element value",
    applicationMode: "automatic",
    implementationTargets: ["Validation Engine", "Scoring", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed automatic star/no-value handling by box overflow.",
  },
  {
    ruleId: "STAR-002",
    sourceId: "WS-FREE-2026",
    printedPage: "7",
    pdfPage: "7",
    section: "General",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger: "Element is in excess.",
    consequence:
      "Element is called then starred with no value; it is not illegal and not penalized by itself.",
    affectedScore: "technical content element value",
    applicationMode: "technical-call",
    implementationTargets: ["Validation Engine", "Scoring", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed excess element no-value and no-separate-penalty treatment.",
  },
  {
    ruleId: "STAR-003",
    sourceId: "WS-FREE-2026",
    printedPage: "39",
    pdfPage: "39",
    section: "Specific procedure for short program",
    categories: ["all"],
    programTypes: ["short"],
    authority: "Technical Panel",
    trigger: "Mandatory element is repeated in short-program procedure context.",
    consequence:
      "Only first mandatory attempt counts; repeated mandatory element is starred and given no value.",
    affectedScore: "technical content element value",
    applicationMode: "technical-call",
    implementationTargets: ["Validation Engine", "Scoring", "Technical Calling"],
    confidence: "confirmed",
    notes: "Confirmed repeated mandatory star treatment in procedure section.",
  },
  {
    ruleId: "STAR-004",
    sourceId: "WS-FREE-2026",
    printedPage: "39",
    pdfPage: "39",
    section: "Specific procedure for short program",
    categories: ["all"],
    programTypes: ["short"],
    authority: "Referee",
    trigger:
      "Element is called after program maximum time from the referee whistle point onward.",
    consequence: "Elements called afterward are invalidated with symbol (*).",
    affectedScore: "technical content element value",
    applicationMode: "manual",
    implementationTargets: [
      "Technical Calling",
      "Validation Engine",
      "Scoring",
      "UI / Referee controls",
    ],
    confidence: "confirmed",
    notes: "Confirmed whistle-to-star invalidation procedure.",
  },
  {
    ruleId: "STAR-005",
    sourceId: "WS-FREE-2026",
    printedPage: "53",
    pdfPage: "53",
    section: "Missing mandatory element",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Panel",
    trigger:
      "Compulsory element omitted/not attempted by last chance in its element group.",
    consequence:
      "Last element of the same group is starred and has no value; missing mandatory penalty also applies.",
    affectedScore: "technical content element value",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "Technical Calling",
      "Scoring",
    ],
    confidence: "confirmed",
    notes: "Confirmed star/no-value with separate penalty for missing mandatory.",
  },
];

const programTimeRules: ProgramTimeRule[] = [
  {
    ruleId: "TIME-001",
    sourceId: "WS-FREE-2026",
    printedPage: "29",
    pdfPage: "29",
    section: "Technical specialist duties",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Technical Specialist",
    trigger: "First movement of the skater.",
    consequence: "TS calls Start.",
    affectedScore: "program timing control",
    applicationMode: "technical-call",
    implementationTargets: ["Technical Calling", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed timing start anchor.",
  },
  {
    ruleId: "TIME-002",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger:
      "Time from start of music to first movement is more than ten seconds.",
    consequence: "Deduct 0.5 point.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: ["Deduction Engine", "UI / Referee controls"],
    confidence: "confirmed",
    notes: "Confirmed music-start delay penalty.",
  },
  {
    ruleId: "TIME-003",
    sourceId: "WS-FREE-2026",
    printedPage: "28",
    pdfPage: "28",
    section: "Penalizations - By the Referee",
    categories: ["all"],
    programTypes: ["short", "long"],
    authority: "Referee",
    trigger: "Program time less than minimum or more than maximum.",
    consequence: "Deduct 0.5 point each 10 seconds or part thereof.",
    affectedScore: "sum: technical content + artistic impression",
    applicationMode: "manual",
    implementationTargets: [
      "Validation Engine",
      "Deduction Engine",
      "UI / Referee controls",
    ],
    confidence: "confirmed",
    notes: "Confirmed duration-penalty logic.",
  },
  {
    ruleId: "TIME-004",
    sourceId: "WS-FREE-2026",
    printedPage: "39",
    pdfPage: "39",
    section: "Specific procedure for short program",
    categories: ["all"],
    programTypes: ["short"],
    authority: "Technical Panel",
    trigger:
      "Program maximum time reached and referee whistle point passed.",
    consequence: "Elements called afterward are invalidated with symbol (*).",
    affectedScore: "technical content element value",
    applicationMode: "technical-call",
    implementationTargets: ["Technical Calling", "Validation Engine", "Scoring"],
    confidence: "confirmed",
    notes: "Confirmed whistle invalidation procedure from short-program protocol.",
  },
];

export const WORLD_SKATE_2026_RULE_PACK: WorldSkate2026DraftRulePack = {
  metadata: {
    federation: "world-skate",
    season: "2026",
    status: "draft",
    sourceRefs: [
      {
        sourceId: "WS-FREE-2026",
        document: "Free Skating Rules for Artistic Skating 2026",
        update: "July 2025",
      },
    ],
    version: "2026-draft",
    key: {
      federation: "world-skate",
      season: "2026",
    },
    name: "World Skate 2026 Free Skating Draft",
    // TODO: Keep false until the draft pack is fully source-confirmed.
    sourceConfirmed: false,
  },
  categories: [],
  elementCatalogue: {
    jumps: [],
    spins: [],
    sequences: [],
    choreographic: [],
  },
  jumpRules: {
    definitions: jumpDefinitions,
    shortProgram: shortProgramJumpRules,
    longProgram: longProgramJumpRules,
    combinations: combinationRules,
    repetitions: repetitionRules,
    rotationCalls,
    bonuses: [],
  },
  spinRules: {
    programRules: spinProgramRules,
    definitions: spinDefinitionRules,
    confirmations: spinConfirmationRules,
    combinations: spinCombinationRules,
    restrictions: spinRestrictionRules,
    difficultPositions: difficultPositionRules,
  },
  sequenceRules: {
    stepProgramRules: stepSequenceProgramRules,
    stepDefinitions: stepSequenceDefinitionRules,
    stepLevels: stepSequenceLevelRules,
    choreographicRules: choreographicSequenceRules,
    confirmations: sequenceConfirmationRules,
    restrictions: sequenceRestrictionRules,
  },
  penaltyRules: {
    refereePenalties: refereePenaltyRules,
    technicalPanelPenalties: technicalPanelPenaltyRules,
    fallPenalties: fallPenaltyRules,
    missingMandatoryElementRules: missingMandatoryElementRules,
    illegalElementRules: illegalElementRules,
    mandatoryPositionRules: mandatoryPositionRules,
    starredElementRules: starredElementRules,
    programTimeRules: programTimeRules,
  },
  disciplines: [],
  programTypes: [],
  limits: {},
  repetitionRules: {},
  requiredElements: {},
  deductions: {},
  elementBaseValues: {},
  goeTables: {},
  pcsRules: {},
  builderProfiles: {},
  objectiveProfiles: {},
  getProgramTypeValidationOverrides: (_programTypeId: ProgramTypeId) => {
    // TODO: No program-type overrides are confirmed for this draft pack yet.
    return null;
  },
};

export const WORLD_SKATE_2026_JUMP_RULES = {
  definitions: jumpDefinitions,
  shortProgram: shortProgramJumpRules,
  longProgram: longProgramJumpRules,
  combinations: combinationRules,
  repetitions: repetitionRules,
  rotationCalls,
  bonuses: [],
};

export const WORLD_SKATE_2026_SPIN_RULES = {
  programRules: spinProgramRules,
  definitions: spinDefinitionRules,
  confirmations: spinConfirmationRules,
  combinations: spinCombinationRules,
  restrictions: spinRestrictionRules,
  difficultPositions: difficultPositionRules,
};

export const WORLD_SKATE_2026_SEQUENCE_RULES = {
  stepProgramRules: stepSequenceProgramRules,
  stepDefinitions: stepSequenceDefinitionRules,
  stepLevels: stepSequenceLevelRules,
  choreographicRules: choreographicSequenceRules,
  confirmations: sequenceConfirmationRules,
  restrictions: sequenceRestrictionRules,
};

export const WORLD_SKATE_2026_PENALTY_RULES = {
  refereePenalties: refereePenaltyRules,
  technicalPanelPenalties: technicalPanelPenaltyRules,
  fallPenalties: fallPenaltyRules,
  missingMandatoryElementRules: missingMandatoryElementRules,
  illegalElementRules: illegalElementRules,
  mandatoryPositionRules: mandatoryPositionRules,
  starredElementRules: starredElementRules,
  programTimeRules: programTimeRules,
};
